### ISSUE TITLE
I would like to know if you can guide me with the following problems

### ISSUE THREAD

**Issue by MercadoXL** [rbaindourov/facebook-marketing-api-example#1]
Hello I would like to list the potential customers of a Facebook Lead Ads Lead form, and I think you have a great code but I would like to see if you can guide me.

when trying to try getAccessToken.php

I get the following:

Login not secure blocked: You can not get an access token or log in to this app from an insecure page. Try re-loading the page as https: //

Question 1 is it mandatory to use SSL?

Question 2 about the config

   "app_id": "ID of an APP related to my Business Manager?",
   "URL": "The URL of my domain?",
   "page_id": "Id of the page that has the forms to obtain the clients?"

Question 3 is there a way to get access to potential customers without requesting a section initiation? . It happens that I want to make a code that runs every day automatically and get potential customers.

Thank you in advance for your help.

**Comment by MercadoXL** [comment]
Hi I have managed to solve some obstacles, by placing SSL I managed to continue forward but now after having my app properly configured, the ad account associated with testing the script I have this error.

Invalid Scopes: manage_pages. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by rbaindourov** [comment]
Hi, Sorry it took me so long to answer you. 
So scopes are basically permissions. Invalid Scope error means you simply have to manage the permissions / scopes on that account. 

I am sure you figured that out already.
